Repository selasdev/lepetinski-front-app, pull requests merged in 2022-07, with the labels that each got.

#2 Feature/homepage components
  public/assets/icons/hamburguer.svg
  public/assets/images/banner.png
  public/assets/images/hero.svg
  public/assets/images/logo.svg
  src/App.tsx
  src/components/atoms/Button/index.styles.tsx
  src/components/atoms/Button/index.tsx
  src/components/molecules/Card/CardIcon/index.styles.tsx
  src/components/molecules/Card/CardIcon/index.tsx
  src/components/molecules/Card/CardIcon/types.ts
  src/components/organisms/BackgroundBanner/index.styles.tsx
  src/components/organisms/BackgroundBanner/index.tsx
  src/components/organisms/Categories/data.ts
  src/components/organisms/Categories/index.styles.tsx
  src/components/organisms/Categories/index.tsx
  src/components/organisms/Hero/index.styles.tsx
  src/components/organisms/Hero/index.tsx
  src/components/organisms/Navbar/index.styles.tsx
  src/components/organisms/Navbar/index.tsx
  src/contexts/Auth/context.tsx
  src/theme/breakpoints.ts
  src/theme/global.ts
  src/theme/theme.ts
  src/views/home/index.tsx
  yarn.lock
Labels: enhancement, help wanted, good first issue

#3 feat: Login and signin created
  package.json
  src/App.tsx
  src/components/atoms/Link/index.tsx
  src/components/organisms/BackgroundBanner/index.tsx
  src/components/organisms/Hero/index.tsx
  src/routes/index.tsx
  src/theme/components.ts
  src/theme/materialPalette.ts
  src/theme/materialTheme.ts
  src/theme/theme.ts
  src/views/Login/index.tsx
  src/views/signIn/index.tsx
  yarn.lock
Labels: enhancement, theming

#4 Feature/listing process
  package-lock.json
  src/components/atoms/Link/index.tsx
  src/components/molecules/Card/CardIcon/index.styles.tsx
  src/components/molecules/Card/CardIcon/index.tsx
  src/components/molecules/Card/CardIcon/types.ts
  src/components/organisms/BackgroundBanner/index.tsx
  src/components/organisms/Categories/__mocks__/data.ts
  src/components/organisms/Categories/data.ts
  src/components/organisms/Categories/index.styles.tsx
  src/components/organisms/Categories/index.tsx
  src/components/organisms/Hero/index.tsx
  src/routes/index.tsx
  src/views/Login/index.tsx
Labels: bug, enhancement, invalid, theming
